//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARP.Ejemplo.Pruebas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARP.Ejemplo.Pruebas.Mensaje", typeof(Mensaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario autenticado..
        /// </summary>
        internal static string AutenticacionExitosa {
            get {
                return ResourceManager.GetString("AutenticacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es invalida..
        /// </summary>
        internal static string ClaveErrada {
            get {
                return ResourceManager.GetString("ClaveErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ha caducado, por favor cámbiela para continuar..
        /// </summary>
        internal static string ContrasenaCaduco {
            get {
                return ResourceManager.GetString("ContrasenaCaduco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos para la autenticacion son nulos..
        /// </summary>
        internal static string DatosEnBlanco {
            get {
                return ResourceManager.GetString("DatosEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos para la autenticacion son nulos..
        /// </summary>
        internal static string DatosEnNull {
            get {
                return ResourceManager.GetString("DatosEnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dominio al que pertenece el usuario es requerido..
        /// </summary>
        internal static string DatosSinEncriptar {
            get {
                return ResourceManager.GetString("DatosSinEncriptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de intentos de acceso superado.
        /// </summary>
        internal static string ExcedeNumeroIntentos {
            get {
                return ResourceManager.GetString("ExcedeNumeroIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception has been thrown by the target of an invocation..
        /// </summary>
        internal static string ServicioNoDisponible {
            get {
                return ResourceManager.GetString("ServicioNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario está bloqueado..
        /// </summary>
        internal static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ó contraseña invalidos..
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dominio al que pertenece el usuario es requerido..
        /// </summary>
        internal static string UsuarioSinDominio {
            get {
                return ResourceManager.GetString("UsuarioSinDominio", resourceCulture);
            }
        }
    }
}
