//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosIniciales", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Datos/")]
    [System.SerializableAttribute()]
    internal partial class DatosIniciales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContrasenaField;
        
        private ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.TIPO_RED TipoRedField;
        
        private string UsuarioLoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.TIPO_RED TipoRed {
            get {
                return this.TipoRedField;
            }
            set {
                if ((this.TipoRedField.Equals(value) != true)) {
                    this.TipoRedField = value;
                    this.RaisePropertyChanged("TipoRed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string UsuarioLogin {
            get {
                return this.UsuarioLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioLoginField, value) != true)) {
                    this.UsuarioLoginField = value;
                    this.RaisePropertyChanged("UsuarioLogin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIPO_RED", Namespace="http://schemas.ARP.AdminSeguridad.com/2010/08/Servicios/")]
    internal enum TIPO_RED : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoEspecificado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extranet = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Intranet = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Datos/")]
    [System.SerializableAttribute()]
    internal partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AutenticadoField;
        
        private ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.CODIGO_RESULTADO_TRANSACCION CodigoResultadoField;
        
        private string MensajeRespuestaField;
        
        private ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool Autenticado {
            get {
                return this.AutenticadoField;
            }
            set {
                if ((this.AutenticadoField.Equals(value) != true)) {
                    this.AutenticadoField = value;
                    this.RaisePropertyChanged("Autenticado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.CODIGO_RESULTADO_TRANSACCION CodigoResultado {
            get {
                return this.CodigoResultadoField;
            }
            set {
                if ((this.CodigoResultadoField.Equals(value) != true)) {
                    this.CodigoResultadoField = value;
                    this.RaisePropertyChanged("CodigoResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Datos/")]
    [System.SerializableAttribute()]
    internal partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActivoField;
        
        private bool BloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        private string ContrasenaField;
        
        private bool ContrasenaCaducaField;
        
        private int ContrasenaCaducidadDiasField;
        
        private bool ContrasenaDebeContenerCharsEspecialesField;
        
        private bool ContrasenaDebeContenerMayusculasField;
        
        private bool ContrasenaDebeContenerMinusculasField;
        
        private bool ContrasenaDebeContenerNumerosField;
        
        private string EmailField;
        
        private System.DateTime FechaCreacionField;
        
        private System.DateTime FechaCreacionContrasenaField;
        
        private int IdField;
        
        private int IntentosConsecutivosField;
        
        private string LoginUsuarioField;
        
        private int LongitudMinimaContrasenaField;
        
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIdentificacionField;
        
        private System.Nullable<bool> ObligarCambioContrasenaField;
        
        private string PreguntaSecretaField;
        
        private string PrimerApellidoField;
        
        private string PrimerNombreField;
        
        private bool RegistroConfirmadoField;
        
        private string RespuestaSecretaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlCambioContrasenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool Bloqueado {
            get {
                return this.BloqueadoField;
            }
            set {
                if ((this.BloqueadoField.Equals(value) != true)) {
                    this.BloqueadoField = value;
                    this.RaisePropertyChanged("Bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool ContrasenaCaduca {
            get {
                return this.ContrasenaCaducaField;
            }
            set {
                if ((this.ContrasenaCaducaField.Equals(value) != true)) {
                    this.ContrasenaCaducaField = value;
                    this.RaisePropertyChanged("ContrasenaCaduca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int ContrasenaCaducidadDias {
            get {
                return this.ContrasenaCaducidadDiasField;
            }
            set {
                if ((this.ContrasenaCaducidadDiasField.Equals(value) != true)) {
                    this.ContrasenaCaducidadDiasField = value;
                    this.RaisePropertyChanged("ContrasenaCaducidadDias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool ContrasenaDebeContenerCharsEspeciales {
            get {
                return this.ContrasenaDebeContenerCharsEspecialesField;
            }
            set {
                if ((this.ContrasenaDebeContenerCharsEspecialesField.Equals(value) != true)) {
                    this.ContrasenaDebeContenerCharsEspecialesField = value;
                    this.RaisePropertyChanged("ContrasenaDebeContenerCharsEspeciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool ContrasenaDebeContenerMayusculas {
            get {
                return this.ContrasenaDebeContenerMayusculasField;
            }
            set {
                if ((this.ContrasenaDebeContenerMayusculasField.Equals(value) != true)) {
                    this.ContrasenaDebeContenerMayusculasField = value;
                    this.RaisePropertyChanged("ContrasenaDebeContenerMayusculas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool ContrasenaDebeContenerMinusculas {
            get {
                return this.ContrasenaDebeContenerMinusculasField;
            }
            set {
                if ((this.ContrasenaDebeContenerMinusculasField.Equals(value) != true)) {
                    this.ContrasenaDebeContenerMinusculasField = value;
                    this.RaisePropertyChanged("ContrasenaDebeContenerMinusculas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool ContrasenaDebeContenerNumeros {
            get {
                return this.ContrasenaDebeContenerNumerosField;
            }
            set {
                if ((this.ContrasenaDebeContenerNumerosField.Equals(value) != true)) {
                    this.ContrasenaDebeContenerNumerosField = value;
                    this.RaisePropertyChanged("ContrasenaDebeContenerNumeros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.DateTime FechaCreacionContrasena {
            get {
                return this.FechaCreacionContrasenaField;
            }
            set {
                if ((this.FechaCreacionContrasenaField.Equals(value) != true)) {
                    this.FechaCreacionContrasenaField = value;
                    this.RaisePropertyChanged("FechaCreacionContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int IntentosConsecutivos {
            get {
                return this.IntentosConsecutivosField;
            }
            set {
                if ((this.IntentosConsecutivosField.Equals(value) != true)) {
                    this.IntentosConsecutivosField = value;
                    this.RaisePropertyChanged("IntentosConsecutivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string LoginUsuario {
            get {
                return this.LoginUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginUsuarioField, value) != true)) {
                    this.LoginUsuarioField = value;
                    this.RaisePropertyChanged("LoginUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int LongitudMinimaContrasena {
            get {
                return this.LongitudMinimaContrasenaField;
            }
            set {
                if ((this.LongitudMinimaContrasenaField.Equals(value) != true)) {
                    this.LongitudMinimaContrasenaField = value;
                    this.RaisePropertyChanged("LongitudMinimaContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NumeroIdentificacion {
            get {
                return this.NumeroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIdentificacionField, value) != true)) {
                    this.NumeroIdentificacionField = value;
                    this.RaisePropertyChanged("NumeroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Nullable<bool> ObligarCambioContrasena {
            get {
                return this.ObligarCambioContrasenaField;
            }
            set {
                if ((this.ObligarCambioContrasenaField.Equals(value) != true)) {
                    this.ObligarCambioContrasenaField = value;
                    this.RaisePropertyChanged("ObligarCambioContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string PreguntaSecreta {
            get {
                return this.PreguntaSecretaField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntaSecretaField, value) != true)) {
                    this.PreguntaSecretaField = value;
                    this.RaisePropertyChanged("PreguntaSecreta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool RegistroConfirmado {
            get {
                return this.RegistroConfirmadoField;
            }
            set {
                if ((this.RegistroConfirmadoField.Equals(value) != true)) {
                    this.RegistroConfirmadoField = value;
                    this.RaisePropertyChanged("RegistroConfirmado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string RespuestaSecreta {
            get {
                return this.RespuestaSecretaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaSecretaField, value) != true)) {
                    this.RespuestaSecretaField = value;
                    this.RaisePropertyChanged("RespuestaSecreta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TipoIdentificacion {
            get {
                return this.TipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIdentificacionField, value) != true)) {
                    this.TipoIdentificacionField = value;
                    this.RaisePropertyChanged("TipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UrlCambioContrasena {
            get {
                return this.UrlCambioContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlCambioContrasenaField, value) != true)) {
                    this.UrlCambioContrasenaField = value;
                    this.RaisePropertyChanged("UrlCambioContrasena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CODIGO_RESULTADO_TRANSACCION", Namespace="http://schemas.ARP.AdminSeguridad.com/2010/08/Servicios/")]
    internal enum CODIGO_RESULTADO_TRANSACCION : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoEspecificado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AplicacionFault", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Faults/")]
    [System.SerializableAttribute()]
    internal partial class AplicacionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosFault", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Faults/")]
    [System.SerializableAttribute()]
    internal partial class DatosFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NegocioFault", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Faults/")]
    [System.SerializableAttribute()]
    internal partial class NegocioFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/AutenticacionSeguridad/", ConfigurationName="SeguridadAutenticacionSvc.SeguridadAutenticacion")]
    internal interface SeguridadAutenticacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ARP.AdminSeguridad.com/2011/05/AutenticacionSeguridad/SeguridadAut" +
            "enticacion/AutenticarUsuario", ReplyAction="http://schemas.ARP.AdminSeguridad.com/2011/05/AutenticacionSeguridad/SeguridadAut" +
            "enticacion/AutenticarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.AplicacionFault), Action="http://ARP.AdminSeguridad.com/2011/05/AplicacionFault", Name="AplicacionFault", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.DatosFault), Action="http://ARP.AdminSeguridad.com/2011/05/DatosFault", Name="DatosFault", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Faults/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.NegocioFault), Action="http://ARP.AdminSeguridad.com/2011/05/NegocioFault", Name="NegocioFault", Namespace="http://schemas.ARP.AdminSeguridad.com/2011/05/Faults/")]
        ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.Resultado AutenticarUsuario(ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.DatosIniciales pDatosIniciales);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SeguridadAutenticacionChannel : ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.SeguridadAutenticacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SeguridadAutenticacionClient : System.ServiceModel.ClientBase<ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.SeguridadAutenticacion>, ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.SeguridadAutenticacion {
        
        public SeguridadAutenticacionClient() {
        }
        
        public SeguridadAutenticacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadAutenticacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadAutenticacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadAutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.Resultado AutenticarUsuario(ARP.Ejemplo.Integracion.SeguridadAutenticacionSvc.DatosIniciales pDatosIniciales) {
            return base.Channel.AutenticarUsuario(pDatosIniciales);
        }
    }
}
