//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARP.Ejemplo.WebExterno.Inicio {
    
    
    public partial class PruebaSEG2000 {
        
        /// <summary>
        /// PruebaSEG20001 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ARP.Ejemplo.WebExterno.Controles.PruebaSEG2000 PruebaSEG20001;
    }
}
