//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARP.Ejemplo.WebExterno.SeguridadSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AplicacionFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
    [System.SerializableAttribute()]
    public partial class AplicacionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NegocioFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
    [System.SerializableAttribute()]
    public partial class NegocioFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
    [System.SerializableAttribute()]
    public partial class DatosFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/", ConfigurationName="SeguridadSvc.Seguridad")]
    public interface Seguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/AutenticarUsuario", ReplyAction="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/AutenticarUsuarioRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.AplicacionFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/AutenticarUsuarioAplic" +
            "acionFaultFault", Name="AplicacionFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.NegocioFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/AutenticarUsuarioNegoc" +
            "ioFaultFault", Name="NegocioFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.DatosFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/AutenticarUsuarioDatos" +
            "FaultFault", Name="DatosFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        ARP.Ejemplo.Comun.Entidades.ResultadoAutenticacion AutenticarUsuario(ARP.Ejemplo.Comun.Entidades.Autenticacion pAutenticacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/CambiarContrasena", ReplyAction="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/CambiarContrasenaRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.AplicacionFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/CambiarContrasenaAplic" +
            "acionFaultFault", Name="AplicacionFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.NegocioFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/CambiarContrasenaNegoc" +
            "ioFaultFault", Name="NegocioFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.DatosFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/CambiarContrasenaDatos" +
            "FaultFault", Name="DatosFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        ARP.Ejemplo.Comun.Entidades.Respuesta CambiarContrasena(ARP.Ejemplo.Comun.Entidades.ContrasenaCambio pCambioContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ObtenerUrl", ReplyAction="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ObtenerUrlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.DatosFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ObtenerUrlDatosFaultFa" +
            "ult", Name="DatosFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.NegocioFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ObtenerUrlNegocioFault" +
            "Fault", Name="NegocioFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.AplicacionFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ObtenerUrlAplicacionFa" +
            "ultFault", Name="AplicacionFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        ARP.Ejemplo.Comun.Entidades.ContrasenaCambio ObtenerUrl(ARP.Ejemplo.Comun.Entidades.ContrasenaCambio pCambioContrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ValidarPreguntaRespues" +
            "taSecreta", ReplyAction="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ValidarPreguntaRespues" +
            "taSecretaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.AplicacionFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ValidarPreguntaRespues" +
            "taSecretaAplicacionFaultFault", Name="AplicacionFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.NegocioFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ValidarPreguntaRespues" +
            "taSecretaNegocioFaultFault", Name="NegocioFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARP.Ejemplo.WebExterno.SeguridadSvc.DatosFault), Action="http://schemas.ARP.Ejemplo.com/2011/02/Seguridad/Seguridad/ValidarPreguntaRespues" +
            "taSecretaDatosFaultFault", Name="DatosFault", Namespace="http://schemas.ARP.com/AutenticacionSeguridad/2010/12/Faults")]
        ARP.Ejemplo.Comun.Entidades.ContrasenaCambio ValidarPreguntaRespuestaSecreta(ARP.Ejemplo.Comun.Entidades.ContrasenaCambio pCambioContrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeguridadChannel : ARP.Ejemplo.WebExterno.SeguridadSvc.Seguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadClient : System.ServiceModel.ClientBase<ARP.Ejemplo.WebExterno.SeguridadSvc.Seguridad>, ARP.Ejemplo.WebExterno.SeguridadSvc.Seguridad {
        
        public SeguridadClient() {
        }
        
        public SeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ARP.Ejemplo.Comun.Entidades.ResultadoAutenticacion AutenticarUsuario(ARP.Ejemplo.Comun.Entidades.Autenticacion pAutenticacion) {
            return base.Channel.AutenticarUsuario(pAutenticacion);
        }
        
        public ARP.Ejemplo.Comun.Entidades.Respuesta CambiarContrasena(ARP.Ejemplo.Comun.Entidades.ContrasenaCambio pCambioContrasena) {
            return base.Channel.CambiarContrasena(pCambioContrasena);
        }
        
        public ARP.Ejemplo.Comun.Entidades.ContrasenaCambio ObtenerUrl(ARP.Ejemplo.Comun.Entidades.ContrasenaCambio pCambioContrasena) {
            return base.Channel.ObtenerUrl(pCambioContrasena);
        }
        
        public ARP.Ejemplo.Comun.Entidades.ContrasenaCambio ValidarPreguntaRespuestaSecreta(ARP.Ejemplo.Comun.Entidades.ContrasenaCambio pCambioContrasena) {
            return base.Channel.ValidarPreguntaRespuestaSecreta(pCambioContrasena);
        }
    }
}
